### ISSUE TITLE
Study problem related to how joint trajectory is defined when calibrating with calibration type 10

### ISSUE THREAD

**Issue by MSECode** [robotology/icub-firmware#534] opened 2024-11-25 14:30 UTC
As shown in this 2 comments:
- https://github.com/robotology/icub-firmware/issues/529#issuecomment-2497126733
- https://github.com/robotology/icub-firmware/issues/529#issuecomment-2486283511

we need to understand the "possible problem" related to how the joint trajectory is defined when using calibration type 10 for calibrating the joint at the hard stop.
One thing to mention is that, from the data we have dumped we have identified this behaviour as a possible problem, but we first need to better analyze that to be sure that it is actually a problem and why it is happening.

cc: @valegagge

**Comment by valegagge** [comment] 2024-11-29 09:50
Checking the code I noticed in the function `JointSet_do_wait_calibration` , the embeddeed motion control performs a `JointSet_do_odometry` and then set the joint in `position control mode` when the hardstop is reached. I guess these two operations are the cause of the change of the joint position and of the trajectory.

@MSECode Can you check and confirm, please?

**Comment by MSECode** [comment] 2024-11-29 13:11
> Checking the code I noticed in the function `JointSet_do_wait_calibration` , the embeddeed motion control performs a `JointSet_do_odometry` and then set the joint in `position control mode` when the hardstop is reached. I guess these two operations are the cause of the change of the joint position and of the trajectory.
> 
> [@MSECode](https://github.com/MSECode) Can you check and confirm, please?

Yes exactly.

**Comment by valegagge** [comment] 2024-11-29 14:47
ok so we can close this issue.

**Closed** 2024-12-03 10:00 UTC
Labels: enhancement, prio:low
